### ISSUE TITLE
No generés assets en development

### ISSUE THREAD

**Issue by roadev** [davidvanegas7/surveyval#1]
Es una mala práctica común entre principiantes xD
no hagas en local: `rake assets:precompile`
los assets por default se compilan con cada cambio en el server webrick que corres en local (`rails s`)

**Comment by davidvanegas7** [comment]
ok

**Comment by davidvanegas7** [comment]
si ves mas errores visibles (diferente al de cargar la cache, que ya me di cuenta que se me fue) me avisas, para ir afinando

**Comment by roadev** [comment]
Dale ^^
Igual limpiás esa vuelta con `rake assets:clean`
